"""Append-only structured edit commands for Phase 2."""

from __future__ import annotations

from datetime import datetime
from uuid import UUID, uuid4

from sqlalchemy import DateTime, ForeignKey, Integer, String, UniqueConstraint, func
from sqlalchemy.dialects.postgresql import JSONB, UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.session import Base


class DocumentCommand(Base):
    """One validated canonical-document mutation.

    Commands are immutable after insertion. Undo and redo create new commands;
    they never rewrite history. ``inverse_payload`` is generated by the server
    from the exact pre-command state rather than trusted from the browser.
    """

    __tablename__ = "document_commands"
    __table_args__ = (
        UniqueConstraint(
            "project_id", "client_request_id", name="uq_document_command_client_request"
        ),
    )

    id: Mapped[UUID] = mapped_column(PG_UUID(as_uuid=True), primary_key=True, default=uuid4)
    project_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    user_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    command_type: Mapped[str] = mapped_column(String(60), nullable=False)
    payload: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    inverse_payload: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    summary: Mapped[str] = mapped_column(String(400), nullable=False, default="")
    target_type: Mapped[str | None] = mapped_column(String(30), nullable=True)
    target_id: Mapped[UUID | None] = mapped_column(PG_UUID(as_uuid=True), nullable=True, index=True)
    batch_id: Mapped[UUID | None] = mapped_column(PG_UUID(as_uuid=True), nullable=True, index=True)
    client_request_id: Mapped[str | None] = mapped_column(String(120), nullable=True)
    document_version_before: Mapped[int] = mapped_column(Integer, nullable=False)
    document_version_after: Mapped[int] = mapped_column(Integer, nullable=False)
    replays_command_id: Mapped[UUID | None] = mapped_column(PG_UUID(as_uuid=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False, index=True
    )
